### ISSUE TITLE
脚本无法正常使用，账号无法登陆

### ISSUE THREAD

**Issue by kiritro** [Dawnnnnnn/bilibili-tools#24]
登录失败，回显为: {'code': -449, 'message': '服务繁忙, 请稍后再试', 'ts':

**Comment by ironyhex** [comment]
#23 

**提问之前请先查找是否有相同的问题或教程**

哔哩哔哩更新了登录接口。
可将main.py中的第57行
`url = "https://passport.bilibili.com/api/v2/oauth2/login"
`
替换为
`url = "https://passport.bilibili.com/api/v3/oauth2/login"
`

**Comment by kiritro** [comment]
> [＃23](https://github.com/Dawnnnnnn/bilibili-tools/issues/23)
> 
> **提问之前请先查找是否有相同的问题或教程**
> 
> 哔哩哔哩哩更新了登录接口。
> 可将main.py中的第57行
> `url = "https://passport.bilibili.com/api/v2/oauth2/login" `
> 替换为
> `url = "https://passport.bilibili.com/api/v3/oauth2/login" `

按照这个修改了，还是一样的情况

**Comment by ironyhex** [comment]
> > [＃23](https://github.com/Dawnnnnnn/bilibili-tools/issues/23)
> > **提问之前请先查找是否有相同的问题或教程**
> > 哔哩哔哩哩哩更新了登录接口。
> > 可将main.py中的第57行
> > `url = "https://passport.bilibili.com/api/v2/oauth2/login" `
> > 替换为
> > `url = "https://passport.bilibili.com/api/v3/oauth2/login" `
> 
> 按照这个修改了，还是一样的情况

哔哩哔哩又改登录接口了，现在只能等原作者更新了

**Comment by Eustiana** [comment]
line34
`str = str + "560c52ccd288fed045859ed18bffd973"`   =>  `str = str + "59b43e04ad6965f34319062b478f83dd"`

所有 `1d8b6e7d45233436`  =>  `4409e2ce8ffd12b8`

目前测试可以登录

**Comment by ironyhex** [comment]
> line34
> `str = str + "560c52ccd288fed045859ed18bffd973"` => `str = str + "59b43e04ad6965f34319062b478f83dd"`
> 
> 所有 `1d8b6e7d45233436` => `4409e2ce8ffd12b8`
> 
> 目前测试可以登录

感谢反馈
2019-12-31 21:07 
登录正常

**Comment by kumitom** [comment]
我现在可以登录，但是无限watch_run错误，不知道大家如何？

**Comment by LoidVC** [comment]
> line34
> `str = str + "560c52ccd288fed045859ed18bffd973"` => `str = str + "59b43e04ad6965f34319062b478f83dd"`
> 
> 所有 `1d8b6e7d45233436` => `4409e2ce8ffd12b8`
> 
> 目前测试可以登录

修改以后反馈这个，请问怎么办？
Task exception was never retrieved
future: <Task finished coro=<login.login() done, defined at beta.py:54> exception=ProxyError(MaxRetryError("HTTPSConnectionPool(host='passport.bilibili.com', port=443): Max retries exceeded with url: /api/oauth2/getKey (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))"))>
Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "D:\Python37\lib\site-packages\urllib3\connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "D:\Python37\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "D:\Python37\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "D:\Python37\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "D:\Python37\lib\http\client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "D:\Python37\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "D:\Python37\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='passport.bilibili.com', port=443): Max retries exceeded with url: /api/oauth2/getKey (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "beta.py", line 56, in login
    user, pwd = await self.get_pwd(login.username, login.password)
  File "beta.py", line 44, in get_pwd
    response = requests.post(url, data=params)
  File "D:\Python37\lib\site-packages\requests\api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "D:\Python37\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Python37\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Python37\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "D:\Python37\lib\site-packages\requests\adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='passport.bilibili.com', port=443): Max retries exceeded with url: /api/oauth2/getKey (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
caseObtain模块出错
{'code': -101, 'message': '账号未登录', 'ttl': 1}
cookie失效,尝试重新登录!
